#!/bin/bash
MYSQL_CMD="mysql -h tidb-1-peer -u root -D test -P 4000"

$MYSQL_CMD -e "drop user if exists us1, us2, us3;"
$MYSQL_CMD -e "drop resource group if exists rgs1;"
$MYSQL_CMD -e "drop resource group if exists rgs2;"
$MYSQL_CMD -e "drop resource group if exists rgs3;"

$MYSQL_CMD -e "create user us1 identified by '1234';"
$MYSQL_CMD -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,PROCESS,REFERENCES,ALTER,SHOW DATABASES,SUPER,EXECUTE,INDEX,CREATE USER,CREATE TABLESPACE,TRIGGER,CREATE VIEW,SHOW       VIEW,CREATE ROLE,DROP ROLE,CREATE TEMPORARY TABLES,LOCK TABLES,      CREATE ROUTINE,ALTER ROUTINE,EVENT,RELOAD,FILE,REPLICATION CLIENT,REPLICATION SLAVE ON *.* TO 'us1';"
$MYSQL_CMD -e "create resource group rgs1 ru_per_sec = 1400000;"
$MYSQL_CMD -e "alter user us1 resource group rgs1;"

$MYSQL_CMD -e "create user us2 identified by '1234';"
$MYSQL_CMD -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,PROCESS,REFERENCES,ALTER,SHOW DATABASES,SUPER,EXECUTE,INDEX,CREATE USER,CREATE TABLESPACE,TRIGGER,CREATE VIEW,SHOW       VIEW,CREATE ROLE,DROP ROLE,CREATE TEMPORARY TABLES,LOCK TABLES,      CREATE ROUTINE,ALTER ROUTINE,EVENT,RELOAD,FILE,REPLICATION CLIENT,REPLICATION SLAVE ON *.* TO 'us2';"
$MYSQL_CMD -e "create resource group rgs2 ru_per_sec = 1400000;"
$MYSQL_CMD -e "alter user us2 resource group rgs2;"

$MYSQL_CMD -e "create user us3 identified by '1234';"
$MYSQL_CMD -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,PROCESS,REFERENCES,ALTER,SHOW DATABASES,SUPER,EXECUTE,INDEX,CREATE USER,CREATE TABLESPACE,TRIGGER,CREATE VIEW,SHOW       VIEW,CREATE ROLE,DROP ROLE,CREATE TEMPORARY TABLES,LOCK TABLES,      CREATE ROUTINE,ALTER ROUTINE,EVENT,RELOAD,FILE,REPLICATION CLIENT,REPLICATION SLAVE ON *.* TO 'us3';"
$MYSQL_CMD -e "create resource group rgs3 ru_per_sec = 1400000;"
$MYSQL_CMD -e "alter user us3 resource group rgs3;"
